const brandColours={"Canon":"#d71920","Nikon":"#f5c400","Sony":"#f7941d","OM System":"#00a7b5","Fujifilm":"#b8b8b8"};
const brandSettings={
"Canon":{modes:"C1 / C2 / C3",af:"Servo AF",detect:"Subject to Detect: Animals",menu:"AF Menu"},
"Nikon":{modes:"U1 / U2 / U3",af:"AF-C",detect:"Subject Detection: Animals",menu:"Custom Settings Menu"},
"Sony":{modes:"Memory Recall 1 / 2 / 3",af:"AF-C",detect:"Subject Recognition: Animal/Bird",menu:"AF/MF Menu"},
"OM System":{modes:"C1 / C2 / C3 / C4",af:"C-AF + Tracking",detect:"Subject Detection: Animals/Birds",menu:"AF Menu"},
"Fujifilm":{modes:"C1–C7",af:"AF-C",detect:"Subject Detection: Animal/Bird",menu:"AF/MF Setting"}};
const genreData={
"Safari & Wildlife":{hero:"Elephant / leopard hero image",images:["Elephant tracking","Bird in flight","Safari vehicle","Dusty sensor care"],sections:["Animal Eye AF","3D / Subject Tracking","Safari Vehicle Shooting","Dust Prevention"],tips:["Use wider AF areas for large animals.","Use faster shutter speeds for unpredictable movement."]},
"Birds in Flight":{hero:"Birds in flight hero image",images:["Bird against sky","Busy background","Wing action","Tracking overlay"],sections:["Bird Detection","Tracking Sensitivity","Fast Shutter Speeds","Busy Background Control"],tips:["Keep the bird inside the AF area.","Use short controlled bursts."]},
"Motorsport":{hero:"Motorsport hero image",images:["Panning car","Motorbike corner","Pit lane","Vehicle detection overlay"],sections:["Vehicle Detection","Panning Setup","High-Speed Burst","Tracking Response"],tips:["Use panning shutter speeds when movement blur is desired.","Use a responsive tracking setup."]},
"Aviation":{hero:"Aircraft hero image",images:["Jet in sky","Prop aircraft","Airshow panning","Aircraft detection"],sections:["Aircraft Detection","Continuous Tracking","Prop Blur Control","Long Lens Stability"],tips:["Avoid shutter speeds that freeze propellers completely.","Use stabilisation and smooth panning."]},
"Landscape":{hero:"Landscape hero image",images:["Tripod scene","Golden hour","Focus bracketing","Histogram exposure"],sections:["Base ISO","Tripod Workflow","Focus Bracketing","Depth of Field"],tips:["Use base ISO and a tripod for maximum quality.","Check corners and foreground sharpness."]},
"Wedding & Portrait":{hero:"Portrait hero image",images:["Eye AF portrait","Low light reception","Candid moment","Shallow depth of field"],sections:["Eye Detection","Low-Light AF","Silent Shooting","Custom Buttons"],tips:["Use eye detection but monitor which eye is selected.","Have a low-light custom mode ready."]},
"Macro":{hero:"Macro hero image",images:["Insect macro","Flower close-up","Focus stacking","Flash setup"],sections:["Manual Focus Aid","Focus Peaking","Flash Sync","Focus Stacking"],tips:["Depth of field is extremely shallow in macro.","Use focus stacking where available."]}};
const demoGradients=[
"radial-gradient(circle at 70% 30%,rgba(255,180,80,.5),transparent 28%),linear-gradient(135deg,#33200f,#090909)",
"radial-gradient(circle at 40% 35%,rgba(60,160,255,.45),transparent 30%),linear-gradient(135deg,#0d2033,#050505)",
"radial-gradient(circle at 65% 35%,rgba(0,180,120,.35),transparent 35%),linear-gradient(135deg,#112b1f,#050505)",
"radial-gradient(circle at 65% 40%,rgba(255,255,255,.25),transparent 30%),linear-gradient(135deg,#202020,#030303)"];
let uploadedImage=null;
document.getElementById("uploadImage").addEventListener("change",e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{uploadedImage=r.result;alert("Image loaded. Click Use Upload on an image panel.");};r.readAsDataURL(file);});
function val(id){return document.getElementById(id).value}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function hexToRgba(hex,a){const c=hex.replace("#","");return `rgba(${parseInt(c.slice(0,2),16)},${parseInt(c.slice(2,4),16)},${parseInt(c.slice(4,6),16)},${a})`}
function page(n,cls,html){return `<section class="page ${cls}" data-page="${String(n).padStart(2,"0")}"><button class="remove" onclick="removePage(this)">Remove page</button>${html}</section>`}
function imageBox(label,idx){return `<div class="image-box" style="background:${demoGradients[idx%demoGradients.length]}"><div class="image-tools"><button onclick="useUpload(this)">Use Upload</button><button onclick="cycleDemo(this)">Demo</button></div><span contenteditable="true">${esc(label)}</span></div>`}
function feature(t,b){return `<div class="feature" contenteditable="true"><strong>${esc(t)}</strong><br>${esc(b)}</div>`}
function mini(t,b){return `<div class="feature" contenteditable="true"><strong>${esc(t)}</strong><p>${esc(b)}</p></div>`}
function settingsTable(rows){return `<table class="table">${rows.map(r=>`<tr><td contenteditable="true">${esc(r[0])}</td><td contenteditable="true">${esc(r[1])}</td></tr>`).join("")}</table>`}
function menuMock(s){return `<div class="menu-mock"><p class="kicker">${esc(s.menu)} mock-up</p><div class="menu-row"><span>AF Operation</span><span>${esc(s.af)}</span></div><div class="menu-row active"><span>Subject Detection</span><span>${esc(s.detect)}</span></div><div class="menu-row"><span>AF Area</span><span>Tracking / Wide</span></div><div class="menu-row"><span>Drive Mode</span><span>High-speed continuous</span></div></div>`}
function footer(){return `<div class="footer"><span>Expert Guidance</span><span>Field Tested</span><span>Practical & Actionable</span><span>Cameracal Services</span></div>`}
function generateGuide(){const brand=val("brand"),model=val("model"),genre=val("genre"),theme=val("theme"),phone=val("phone"),website=val("website"),length=parseInt(val("length"));const accent=brandColours[brand],s=brandSettings[brand],g=genreData[genre];document.documentElement.style.setProperty("--accent",accent);document.documentElement.style.setProperty("--accent-soft",hexToRgba(accent,.22));document.body.classList.toggle("light",theme==="light");
let pages=[
page(1,"hero",`<div class="logo">CAMERA<span>CAL</span><small>SERVICES</small></div><div class="camera-brand">${esc(brand)}</div><h2 contenteditable="true">${esc(model)}<br>${esc(genre)}<br>Setup Guide</h2><p contenteditable="true">Optimise your camera. Capture more. Miss less.</p>${imageBox(g.hero,0)}<p class="kicker">Practical settings | Field tested | Real world results</p>`),
page(2,"",`<p class="kicker">Welcome</p><h3 contenteditable="true">Get prepared before you travel</h3><p contenteditable="true">This guide gives photographers a practical starting point for configuring the ${esc(brand)} ${esc(model)} for ${esc(genre.toLowerCase())}. It is a field-focused setup guide, not a replacement for the manufacturer manual.</p>${feature("Recommended AF Mode",s.af)}${feature("Subject Detection",s.detect)}${feature("Custom Mode Storage",`Program these settings to ${s.modes} for quick field access.`)}<div class="tip" contenteditable="true">Cameracal Tip: Set up, test and practise before departure.</div>`),
page(3,"",`<p class="kicker">Problem Solving</p><h3 contenteditable="true">Why cameras miss focus</h3><div class="grid2">${mini("Busy backgrounds","Grass, branches and high contrast edges can pull AF away from the subject.")}${mini("Erratic movement","Wildlife rarely moves predictably. Tracking setup matters.")}${mini("Low contrast","Similar colour subjects can reduce AF confidence.")}${mini("Lens stability","Long lenses need support, speed and VR/IBIS setup.")}</div>${imageBox("Focus miss / field example",1)}`),
page(4,"",`<p class="kicker">Core Setup</p><h3 contenteditable="true">${esc(g.sections[0])} best settings</h3>${settingsTable([["AF Mode",s.af],["Detection",s.detect],["AF Area","Wide / Tracking area depending on subject size"],["Drive Mode","High-speed continuous"]])}${menuMock(s)}<div class="tip" contenteditable="true">${esc(g.tips[0])}</div>`),
page(5,"",`<p class="kicker">Configurations</p><h3 contenteditable="true">Recommended presets</h3>${feature("General Wildlife",`${s.af}, Tracking, Animals, Wide Area, High-speed continuous`)}${feature("Fast Action",`${s.af}, Tracking, faster shutter speed, responsive AF`)}${feature("Low Light","Wider AF area, Auto ISO, stabilisation on, controlled burst")}<div class="tip" contenteditable="true">Store your most-used setups before travel.</div>`),
page(6,"",`<p class="kicker">Action Setup</p><h3 contenteditable="true">${esc(g.sections[1])}</h3><ul contenteditable="true"><li>Use continuous autofocus.</li><li>Use subject detection where available.</li><li>Keep the subject inside the active AF area.</li><li>Use a high enough shutter speed to freeze movement.</li></ul>${imageBox(g.images[1],2)}`),
page(7,"",`<p class="kicker">Field Technique</p><h3 contenteditable="true">${esc(g.sections[2])}</h3><ul contenteditable="true"><li>Support long lenses using a beanbag or monopod.</li><li>Pre-focus on likely subject positions.</li><li>Watch for heat haze, dust and vehicle vibration.</li><li>Use stabilisation appropriate for panning or static subjects.</li></ul>${imageBox(g.images[2],3)}`),
page(8,"",`<p class="kicker">Lens Notes</p><h3 contenteditable="true">Recommended lens setup</h3>${settingsTable([["Long telephoto","Stabilisation on, fast shutter speed, support lens well"],["Zoom lenses","Check performance at both wide and telephoto ends"],["Fast primes","Use eye detection carefully at shallow depth of field"]])}<div class="tip" contenteditable="true">Test your actual camera/lens combination before travel.</div>`),
page(9,"",`<p class="kicker">Essential Menu Settings</p><h3 contenteditable="true">Do not overlook these</h3>${settingsTable([["AF Operation",s.af],["Subject Detection",s.detect],["Drive Mode","High-speed continuous"],["Back Button AF","Recommended for advanced control"],["Metering","Evaluative / Matrix / Multi"]])}`),
page(10,"",`<p class="kicker">Care & Reliability</p><h3 contenteditable="true">${esc(g.sections[3])}</h3><ul contenteditable="true"><li>Check and clean the sensor before travel.</li><li>Avoid changing lenses in dusty wind.</li><li>Use a filtered blower only when appropriate.</li><li>Carry spare batteries, cards and a cleaning cloth.</li></ul>${imageBox(g.images[3],0)}`),
page(11,"",`<p class="kicker">Custom Controls</p><h3 contenteditable="true">Button setup suggestion</h3>${settingsTable([["AF-ON","Back Button Focus"],["Joystick","Move AF point"],["Custom button","Subject detection toggle"],["Quick Menu","Drive, ISO, AF Area, Detection"]])}${imageBox("Rear camera controls",1)}`),
page(12,"",`<p class="kicker">Ready for Adventure</p><h3 contenteditable="true">Prepare. Practise. Capture.</h3><p contenteditable="true">The best camera in the world will not save poor preparation. Know your autofocus setup before the trip and your chances of success increase dramatically.</p><div class="logo">CAMERA<span>CAL</span><small>SERVICES</small></div><p contenteditable="true">Camera Calibration • Sensor Cleaning • Training • Setup Support</p><p><strong>${esc(phone)}</strong><br>${esc(website)}</p>`)
];document.getElementById("guide").innerHTML=pages.slice(0,length).join("")+footer();renumberPages()}
function removePage(btn){btn.closest(".page").remove();renumberPages()}
function renumberPages(){[...document.querySelectorAll(".page")].forEach((p,i)=>p.dataset.page=String(i+1).padStart(2,"0"))}
function addCustomPage(){const guide=document.getElementById("guide"),f=guide.querySelector(".footer"),n=document.querySelectorAll(".page").length+1;f.insertAdjacentHTML("beforebegin",page(n,"",`<p class="kicker">Custom Section</p><h3 contenteditable="true">New Guide Page</h3><p contenteditable="true">Add your own text, settings and field notes here.</p>${imageBox("Custom image",0)}`));renumberPages()}
function useUpload(btn){if(!uploadedImage){alert("Upload an image first using the control panel.");return}const box=btn.closest(".image-box");box.style.backgroundImage=`linear-gradient(to top,rgba(0,0,0,.45),transparent),url('${uploadedImage}')`;box.style.backgroundSize="cover";box.style.backgroundPosition="center"}
function cycleDemo(btn){const box=btn.closest(".image-box");box.style.background=demoGradients[Math.floor(Math.random()*demoGradients.length)]}
function downloadStandalone(){const html="<!DOCTYPE html><html>"+document.documentElement.innerHTML+"</html>";const blob=new Blob([html],{type:"text/html"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="cameracal-guide-editable.html";a.click();URL.revokeObjectURL(url)}
generateGuide();
